//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MnemoProject.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MnemoProject.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string @__LanguageNativeName {
            get {
                return ResourceManager.GetString("__LanguageNativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load language file, using default language.
        /// </summary>
        public static string Error_FailedToLoadLanguage {
            get {
                return ResourceManager.GetString("Error_FailedToLoadLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language file not found, using default language.
        /// </summary>
        public static string Error_LanguageFileNotFound {
            get {
                return ResourceManager.GetString("Error_LanguageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string MainWindow_QuickActions {
            get {
                return ResourceManager.GetString("MainWindow_QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Shift + C.
        /// </summary>
        public static string MainWindow_ShortcutKey {
            get {
                return ResourceManager.GetString("MainWindow_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Menu.
        /// </summary>
        public static string MainWindow_ShortcutMenu {
            get {
                return ResourceManager.GetString("MainWindow_ShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemo.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string Settings_About_AppVersion {
            get {
                return ResourceManager.GetString("Settings_About_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons Non-Commercial License.
        /// </summary>
        public static string Settings_About_CC_License {
            get {
                return ResourceManager.GetString("Settings_About_CC_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Settings_About_Documentation {
            get {
                return ResourceManager.GetString("Settings_About_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Settings_About_Home {
            get {
                return ResourceManager.GetString("Settings_About_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Settings_About_License {
            get {
                return ResourceManager.GetString("Settings_About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is licensed under a combination of the MIT and Creative Commons Non-Commercial (BY-NC) licenses. You can freely modify and use it for non-commercial purposes, but it cannot be sold or used for commercial gain. This keeps the software free and open source. For more information, see the full MIT License and Creative Commons Non-Commercial License.
        /// </summary>
        public static string Settings_About_License_Text {
            get {
                return ResourceManager.GetString("Settings_About_License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT License.
        /// </summary>
        public static string Settings_About_MIT_License {
            get {
                return ResourceManager.GetString("Settings_About_MIT_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Settings_About_Support {
            get {
                return ResourceManager.GetString("Settings_About_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &amp; Support.
        /// </summary>
        public static string Settings_About_Title {
            get {
                return ResourceManager.GetString("Settings_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Settings_About_Tutorials {
            get {
                return ResourceManager.GetString("Settings_About_Tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpages.
        /// </summary>
        public static string Settings_About_Webpages {
            get {
                return ResourceManager.GetString("Settings_About_Webpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &amp; Support.
        /// </summary>
        public static string Settings_AboutSupport {
            get {
                return ResourceManager.GetString("Settings_AboutSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string Settings_AI_API_Key {
            get {
                return ResourceManager.GetString("Settings_AI_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access AI features for free, you will need to obtain your own API key from the selected model (completely free for personal use). Providing free access to users incurs significant costs, so this step is sadly necessary, but it only needs to be done once. Please note that AI features may also produce false or unexpected responses.
        /// </summary>
        public static string Settings_AI_API_Warning {
            get {
                return ResourceManager.GetString("Settings_AI_API_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear AI Usage History.
        /// </summary>
        public static string Settings_AI_Clear_History {
            get {
                return ResourceManager.GetString("Settings_AI_Clear_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AI Features.
        /// </summary>
        public static string Settings_AI_Enable {
            get {
                return ResourceManager.GetString("Settings_AI_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be enabled for AI tools to be accessible.
        /// </summary>
        public static string Settings_AI_Enable_Description {
            get {
                return ResourceManager.GetString("Settings_AI_Enable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These features are experimental and may not function as intended. Additionally, there is no guarantee that they will be included in future updates..
        /// </summary>
        public static string Settings_AI_Experimental_Warning {
            get {
                return ResourceManager.GetString("Settings_AI_Experimental_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Features.
        /// </summary>
        public static string Settings_AI_Features {
            get {
                return ResourceManager.GetString("Settings_AI_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Information.
        /// </summary>
        public static string Settings_AI_Important_Info {
            get {
                return ResourceManager.GetString("Settings_AI_Important_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API key is stored locally and never shared.
        /// </summary>
        public static string Settings_AI_Key_Storage {
            get {
                return ResourceManager.GetString("Settings_AI_Key_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locally process data when possible.
        /// </summary>
        public static string Settings_AI_Local_Processing {
            get {
                return ResourceManager.GetString("Settings_AI_Local_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, smaller AI tasks will be processed on your device for better privacy.
        /// </summary>
        public static string Settings_AI_Local_Processing_Desc {
            get {
                return ResourceManager.GetString("Settings_AI_Local_Processing_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Model Settings.
        /// </summary>
        public static string Settings_AI_Model_Settings {
            get {
                return ResourceManager.GetString("Settings_AI_Model_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Provider.
        /// </summary>
        public static string Settings_AI_Provider {
            get {
                return ResourceManager.GetString("Settings_AI_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthropic (Claude).
        /// </summary>
        public static string Settings_AI_Provider_Anthropic {
            get {
                return ResourceManager.GetString("Settings_AI_Provider_Anthropic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini Pro.
        /// </summary>
        public static string Settings_AI_Provider_Gemini {
            get {
                return ResourceManager.GetString("Settings_AI_Provider_Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI (GPT-4).
        /// </summary>
        public static string Settings_AI_Provider_OpenAI {
            get {
                return ResourceManager.GetString("Settings_AI_Provider_OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save AI usage data.
        /// </summary>
        public static string Settings_AI_Save_Usage {
            get {
                return ResourceManager.GetString("Settings_AI_Save_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, your AI usage will be saved in your account to improve future results.
        /// </summary>
        public static string Settings_AI_Save_Usage_Desc {
            get {
                return ResourceManager.GetString("Settings_AI_Save_Usage_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage &amp; Privacy.
        /// </summary>
        public static string Settings_AI_Usage_Privacy {
            get {
                return ResourceManager.GetString("Settings_AI_Usage_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Settings_AI_Verify {
            get {
                return ResourceManager.GetString("Settings_AI_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure automatic flashcard progression.
        /// </summary>
        public static string Settings_AutoPlay_Description {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval duration.
        /// </summary>
        public static string Settings_AutoPlay_IntervalDuration {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_IntervalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds between cards (for Interval mode).
        /// </summary>
        public static string Settings_AutoPlay_IntervalDuration_Desc {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_IntervalDuration_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Play Mode.
        /// </summary>
        public static string Settings_AutoPlay_Mode {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Settings_AutoPlay_Mode_Interval {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Mode_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-play mode.
        /// </summary>
        public static string Settings_AutoPlay_Mode_Label {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Mode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.
        /// </summary>
        public static string Settings_AutoPlay_Mode_Smart {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Mode_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Settings_AutoPlay_Mode_Timer {
            get {
                return ResourceManager.GetString("Settings_AutoPlay_Mode_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        public static string Settings_Backup_Create {
            get {
                return ResourceManager.GetString("Settings_Backup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securely back up and restore your data.
        /// </summary>
        public static string Settings_Backup_Description {
            get {
                return ResourceManager.GetString("Settings_Backup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup: {0}.
        /// </summary>
        public static string Settings_Backup_LastBackup {
            get {
                return ResourceManager.GetString("Settings_Backup_LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string Settings_Backup_Restore {
            get {
                return ResourceManager.GetString("Settings_Backup_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; Restore.
        /// </summary>
        public static string Settings_Backup_Title {
            get {
                return ResourceManager.GetString("Settings_Backup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string Settings_Cache_Clear {
            get {
                return ResourceManager.GetString("Settings_Cache_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary storage for frequently accessed data.
        /// </summary>
        public static string Settings_Cache_Description {
            get {
                return ResourceManager.GetString("Settings_Cache_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Management.
        /// </summary>
        public static string Settings_Cache_Management {
            get {
                return ResourceManager.GetString("Settings_Cache_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current cache size: {0}.
        /// </summary>
        public static string Settings_Cache_Size {
            get {
                return ResourceManager.GetString("Settings_Cache_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data &amp; Storage.
        /// </summary>
        public static string Settings_DataStorage {
            get {
                return ResourceManager.GetString("Settings_DataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental.
        /// </summary>
        public static string Settings_Experimental {
            get {
                return ResourceManager.GetString("Settings_Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your default export settings.
        /// </summary>
        public static string Settings_Export_Description {
            get {
                return ResourceManager.GetString("Settings_Export_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default export format.
        /// </summary>
        public static string Settings_Export_Format {
            get {
                return ResourceManager.GetString("Settings_Export_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anki (.apkg).
        /// </summary>
        public static string Settings_Export_Format_Anki {
            get {
                return ResourceManager.GetString("Settings_Export_Format_Anki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quizlet (.qzl).
        /// </summary>
        public static string Settings_Export_Format_Quizlet {
            get {
                return ResourceManager.GetString("Settings_Export_Format_Quizlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (.fcs).
        /// </summary>
        public static string Settings_Export_Format_Standard {
            get {
                return ResourceManager.GetString("Settings_Export_Format_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string Settings_Export_Options {
            get {
                return ResourceManager.GetString("Settings_Export_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to apply language changes.
        /// </summary>
        public static string Settings_Language_RestartRequired {
            get {
                return ResourceManager.GetString("Settings_Language_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred application language.
        /// </summary>
        public static string Settings_Language_Select {
            get {
                return ResourceManager.GetString("Settings_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Settings_Preferences {
            get {
                return ResourceManager.GetString("Settings_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcard Preferences.
        /// </summary>
        public static string Settings_Preferences_Title {
            get {
                return ResourceManager.GetString("Settings_Preferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure spaced repetition reminders.
        /// </summary>
        public static string Settings_Review_Description {
            get {
                return ResourceManager.GetString("Settings_Review_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable review reminders.
        /// </summary>
        public static string Settings_Review_Enable {
            get {
                return ResourceManager.GetString("Settings_Review_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends notifications when it&apos;s time to review your flashcards.
        /// </summary>
        public static string Settings_Review_Enable_Desc {
            get {
                return ResourceManager.GetString("Settings_Review_Enable_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet hours.
        /// </summary>
        public static string Settings_Review_QuietHours {
            get {
                return ResourceManager.GetString("Settings_Review_QuietHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Settings_Review_QuietHours_To {
            get {
                return ResourceManager.GetString("Settings_Review_QuietHours_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Reminders.
        /// </summary>
        public static string Settings_Review_Reminders {
            get {
                return ResourceManager.GetString("Settings_Review_Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Settings_Storage_Change {
            get {
                return ResourceManager.GetString("Settings_Storage_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        public static string Settings_Storage_Location {
            get {
                return ResourceManager.GetString("Settings_Storage_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where your flashcards, quizzes, and other data are stored.
        /// </summary>
        public static string Settings_Storage_Location_Desc {
            get {
                return ResourceManager.GetString("Settings_Storage_Location_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% of available space used ({1} free).
        /// </summary>
        public static string Settings_Storage_SpaceUsed {
            get {
                return ResourceManager.GetString("Settings_Storage_SpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage &amp; Data.
        /// </summary>
        public static string Settings_Storage_Title {
            get {
                return ResourceManager.GetString("Settings_Storage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-play audio.
        /// </summary>
        public static string Settings_Study_AutoPlayAudio {
            get {
                return ResourceManager.GetString("Settings_Study_AutoPlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, audio files on flashcards will play automatically.
        /// </summary>
        public static string Settings_Study_AutoPlayAudio_Desc {
            get {
                return ResourceManager.GetString("Settings_Study_AutoPlayAudio_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards per session.
        /// </summary>
        public static string Settings_Study_CardsPerSession {
            get {
                return ResourceManager.GetString("Settings_Study_CardsPerSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of cards to study in one session.
        /// </summary>
        public static string Settings_Study_CardsPerSession_Desc {
            get {
                return ResourceManager.GetString("Settings_Study_CardsPerSession_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your flashcard study behavior.
        /// </summary>
        public static string Settings_Study_Description {
            get {
                return ResourceManager.GetString("Settings_Study_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preload multimedia content.
        /// </summary>
        public static string Settings_Study_PreloadMultimedia {
            get {
                return ResourceManager.GetString("Settings_Study_PreloadMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improves performance by loading multimedia before playing with large decks.
        /// </summary>
        public static string Settings_Study_PreloadMultimedia_Desc {
            get {
                return ResourceManager.GetString("Settings_Study_PreloadMultimedia_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Session.
        /// </summary>
        public static string Settings_Study_Session {
            get {
                return ResourceManager.GetString("Settings_Study_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred application theme.
        /// </summary>
        public static string Settings_Theme_Select {
            get {
                return ResourceManager.GetString("Settings_Theme_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Effects.
        /// </summary>
        public static string Settings_UIEffects {
            get {
                return ResourceManager.GetString("Settings_UIEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling animations may improve performance on older devices.
        /// </summary>
        public static string Settings_UIEffects_AnimationsHint {
            get {
                return ResourceManager.GetString("Settings_UIEffects_AnimationsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure animation and visual effects settings.
        /// </summary>
        public static string Settings_UIEffects_Description {
            get {
                return ResourceManager.GetString("Settings_UIEffects_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable animations.
        /// </summary>
        public static string Settings_UIEffects_EnableAnimations {
            get {
                return ResourceManager.GetString("Settings_UIEffects_EnableAnimations", resourceCulture);
            }
        }
    }
}
